# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Mitglied.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mitglied(object):
    def setupUi(self, Mitglied):
        Mitglied.setObjectName(_fromUtf8("Mitglied"))
        Mitglied.resize(456, 575)
        self.gridLayout_6 = QtGui.QGridLayout(Mitglied)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.toolBox = QtGui.QToolBox(Mitglied)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.pgPerson = QtGui.QWidget()
        self.pgPerson.setGeometry(QtCore.QRect(0, 0, 438, 307))
        self.pgPerson.setObjectName(_fromUtf8("pgPerson"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pgPerson)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radNatuerlichePerson = QtGui.QRadioButton(self.pgPerson)
        self.radNatuerlichePerson.setObjectName(_fromUtf8("radNatuerlichePerson"))
        self.horizontalLayout_2.addWidget(self.radNatuerlichePerson)
        self.radJuristischePerson = QtGui.QRadioButton(self.pgPerson)
        self.radJuristischePerson.setObjectName(_fromUtf8("radJuristischePerson"))
        self.horizontalLayout_2.addWidget(self.radJuristischePerson)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.toolBox.addItem(self.pgPerson, _fromUtf8(""))
        self.pgAdresse = QtGui.QWidget()
        self.pgAdresse.setGeometry(QtCore.QRect(0, 0, 438, 307))
        self.pgAdresse.setObjectName(_fromUtf8("pgAdresse"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pgAdresse)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label = QtGui.QLabel(self.pgAdresse)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txlStrasse = QtGui.QLineEdit(self.pgAdresse)
        self.txlStrasse.setObjectName(_fromUtf8("txlStrasse"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.txlStrasse)
        self.label_3 = QtGui.QLabel(self.pgAdresse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.txlHnr = QtGui.QLineEdit(self.pgAdresse)
        self.txlHnr.setObjectName(_fromUtf8("txlHnr"))
        self.horizontalLayout_3.addWidget(self.txlHnr)
        self.label_4 = QtGui.QLabel(self.pgAdresse)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txlHnrZusatz = QtGui.QLineEdit(self.pgAdresse)
        self.txlHnrZusatz.setObjectName(_fromUtf8("txlHnrZusatz"))
        self.horizontalLayout_3.addWidget(self.txlHnrZusatz)
        self.formLayout_6.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.pgAdresse)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txlAdresszusatz = QtGui.QLineEdit(self.pgAdresse)
        self.txlAdresszusatz.setObjectName(_fromUtf8("txlAdresszusatz"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.txlAdresszusatz)
        self.verticalLayout.addLayout(self.formLayout_6)
        self.groupBox = QtGui.QGroupBox(self.pgAdresse)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.radOrtCbx = QtGui.QRadioButton(self.groupBox)
        self.radOrtCbx.setObjectName(_fromUtf8("radOrtCbx"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.radOrtCbx)
        self.cbxOrt = QtGui.QComboBox(self.groupBox)
        self.cbxOrt.setObjectName(_fromUtf8("cbxOrt"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbxOrt)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.radOrtNeu = QtGui.QRadioButton(self.groupBox)
        self.radOrtNeu.setObjectName(_fromUtf8("radOrtNeu"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.radOrtNeu)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labPlz = QtGui.QLabel(self.groupBox)
        self.labPlz.setObjectName(_fromUtf8("labPlz"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labPlz)
        self.txlPlz = QtGui.QLineEdit(self.groupBox)
        self.txlPlz.setObjectName(_fromUtf8("txlPlz"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txlPlz)
        self.labOrt = QtGui.QLabel(self.groupBox)
        self.labOrt.setObjectName(_fromUtf8("labOrt"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labOrt)
        self.txlOrt = QtGui.QLineEdit(self.groupBox)
        self.txlOrt.setObjectName(_fromUtf8("txlOrt"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txlOrt)
        self.labLand = QtGui.QLabel(self.groupBox)
        self.labLand.setObjectName(_fromUtf8("labLand"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labLand)
        self.cbxLand = QtGui.QComboBox(self.groupBox)
        self.cbxLand.setObjectName(_fromUtf8("cbxLand"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbxLand)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.formLayout)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 288, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.toolBox.addItem(self.pgAdresse, _fromUtf8(""))
        self.pgKontakt = QtGui.QWidget()
        self.pgKontakt.setGeometry(QtCore.QRect(0, 0, 438, 307))
        self.pgKontakt.setObjectName(_fromUtf8("pgKontakt"))
        self.gridLayout_3 = QtGui.QGridLayout(self.pgKontakt)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabKontakt = QtGui.QTabWidget(self.pgKontakt)
        self.tabKontakt.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabKontakt.setObjectName(_fromUtf8("tabKontakt"))
        self.tabEmail = QtGui.QWidget()
        self.tabEmail.setObjectName(_fromUtf8("tabEmail"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabEmail)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblEmail = QtGui.QTableView(self.tabEmail)
        self.tblEmail.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblEmail.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tblEmail.setObjectName(_fromUtf8("tblEmail"))
        self.gridLayout_2.addWidget(self.tblEmail, 0, 0, 1, 1)
        self.tabKontakt.addTab(self.tabEmail, _fromUtf8(""))
        self.tabTelefon = QtGui.QWidget()
        self.tabTelefon.setObjectName(_fromUtf8("tabTelefon"))
        self.gridLayout = QtGui.QGridLayout(self.tabTelefon)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblTelefon = QtGui.QTableView(self.tabTelefon)
        self.tblTelefon.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblTelefon.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tblTelefon.setObjectName(_fromUtf8("tblTelefon"))
        self.gridLayout.addWidget(self.tblTelefon, 0, 0, 1, 1)
        self.tabKontakt.addTab(self.tabTelefon, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabKontakt, 0, 0, 1, 1)
        self.toolBox.addItem(self.pgKontakt, _fromUtf8(""))
        self.pgMitgliedschaft = QtGui.QWidget()
        self.pgMitgliedschaft.setGeometry(QtCore.QRect(0, 0, 438, 344))
        self.pgMitgliedschaft.setObjectName(_fromUtf8("pgMitgliedschaft"))
        self.formLayout_2 = QtGui.QFormLayout(self.pgMitgliedschaft)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txlMitgliedsnummer = QtGui.QLineEdit(self.pgMitgliedschaft)
        self.txlMitgliedsnummer.setEnabled(True)
        self.txlMitgliedsnummer.setReadOnly(True)
        self.txlMitgliedsnummer.setObjectName(_fromUtf8("txlMitgliedsnummer"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txlMitgliedsnummer)
        self.label_13 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.cbxKategorie = QtGui.QComboBox(self.pgMitgliedschaft)
        self.cbxKategorie.setObjectName(_fromUtf8("cbxKategorie"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbxKategorie)
        self.label_7 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cbxBeitragsgruppe = QtGui.QComboBox(self.pgMitgliedschaft)
        self.cbxBeitragsgruppe.setObjectName(_fromUtf8("cbxBeitragsgruppe"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbxBeitragsgruppe)
        self.label_9 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.txlBeitrag = QtGui.QLineEdit(self.pgMitgliedschaft)
        self.txlBeitrag.setReadOnly(True)
        self.txlBeitrag.setObjectName(_fromUtf8("txlBeitrag"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.txlBeitrag)
        self.label_10 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_10)
        self.txlIndividuellerBeitrag = QtGui.QLineEdit(self.pgMitgliedschaft)
        self.txlIndividuellerBeitrag.setObjectName(_fromUtf8("txlIndividuellerBeitrag"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.txlIndividuellerBeitrag)
        self.label_15 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_15)
        self.cbxZahlungsart = QtGui.QComboBox(self.pgMitgliedschaft)
        self.cbxZahlungsart.setObjectName(_fromUtf8("cbxZahlungsart"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.cbxZahlungsart)
        self.label_17 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_17)
        self.cbxZahlweise = QtGui.QComboBox(self.pgMitgliedschaft)
        self.cbxZahlweise.setObjectName(_fromUtf8("cbxZahlweise"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.cbxZahlweise)
        self.label_11 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_11)
        self.dateEintrittsDatum = QtGui.QDateEdit(self.pgMitgliedschaft)
        self.dateEintrittsDatum.setCalendarPopup(True)
        self.dateEintrittsDatum.setObjectName(_fromUtf8("dateEintrittsDatum"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.dateEintrittsDatum)
        self.label_12 = QtGui.QLabel(self.pgMitgliedschaft)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dateAustrittsDatum = QtGui.QDateEdit(self.pgMitgliedschaft)
        self.dateAustrittsDatum.setDateTime(QtCore.QDateTime(QtCore.QDate(2099, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateAustrittsDatum.setDate(QtCore.QDate(2099, 12, 31))
        self.dateAustrittsDatum.setCalendarPopup(True)
        self.dateAustrittsDatum.setObjectName(_fromUtf8("dateAustrittsDatum"))
        self.horizontalLayout.addWidget(self.dateAustrittsDatum)
        self.btnAustrittHeute = QtGui.QPushButton(self.pgMitgliedschaft)
        self.btnAustrittHeute.setObjectName(_fromUtf8("btnAustrittHeute"))
        self.horizontalLayout.addWidget(self.btnAustrittHeute)
        self.formLayout_2.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.lblAustrittsgrund = QtGui.QLabel(self.pgMitgliedschaft)
        self.lblAustrittsgrund.setObjectName(_fromUtf8("lblAustrittsgrund"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.lblAustrittsgrund)
        self.cbxAustrittsgrund = QtGui.QComboBox(self.pgMitgliedschaft)
        self.cbxAustrittsgrund.setObjectName(_fromUtf8("cbxAustrittsgrund"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.cbxAustrittsgrund)
        self.toolBox.addItem(self.pgMitgliedschaft, _fromUtf8(""))
        self.pgBankverbindung = QtGui.QWidget()
        self.pgBankverbindung.setGeometry(QtCore.QRect(0, 0, 438, 307))
        self.pgBankverbindung.setObjectName(_fromUtf8("pgBankverbindung"))
        self.formLayout_3 = QtGui.QFormLayout(self.pgBankverbindung)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.pgBankverbindung)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txlKontonummer = QtGui.QLineEdit(self.pgBankverbindung)
        self.txlKontonummer.setObjectName(_fromUtf8("txlKontonummer"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txlKontonummer)
        self.label_14 = QtGui.QLabel(self.pgBankverbindung)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.txlBlz = QtGui.QLineEdit(self.pgBankverbindung)
        self.txlBlz.setObjectName(_fromUtf8("txlBlz"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.txlBlz)
        self.label_16 = QtGui.QLabel(self.pgBankverbindung)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.txlInstitut = QtGui.QLineEdit(self.pgBankverbindung)
        self.txlInstitut.setReadOnly(False)
        self.txlInstitut.setObjectName(_fromUtf8("txlInstitut"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.txlInstitut)
        self.label_18 = QtGui.QLabel(self.pgBankverbindung)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_18)
        self.txlKontoInhaber = QtGui.QLineEdit(self.pgBankverbindung)
        self.txlKontoInhaber.setObjectName(_fromUtf8("txlKontoInhaber"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.txlKontoInhaber)
        self.label_19 = QtGui.QLabel(self.pgBankverbindung)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_19)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dateEinzugsermaechtigung = QtGui.QDateEdit(self.pgBankverbindung)
        self.dateEinzugsermaechtigung.setCalendarPopup(True)
        self.dateEinzugsermaechtigung.setObjectName(_fromUtf8("dateEinzugsermaechtigung"))
        self.horizontalLayout_4.addWidget(self.dateEinzugsermaechtigung)
        self.btnEinzugsermaechtigungHeute = QtGui.QPushButton(self.pgBankverbindung)
        self.btnEinzugsermaechtigungHeute.setObjectName(_fromUtf8("btnEinzugsermaechtigungHeute"))
        self.horizontalLayout_4.addWidget(self.btnEinzugsermaechtigungHeute)
        self.formLayout_3.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtGui.QLabel(self.pgBankverbindung)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_20 = QtGui.QLabel(self.pgBankverbindung)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self.txlIban = QtGui.QLineEdit(self.pgBankverbindung)
        self.txlIban.setObjectName(_fromUtf8("txlIban"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txlIban)
        self.txlBic = QtGui.QLineEdit(self.pgBankverbindung)
        self.txlBic.setObjectName(_fromUtf8("txlBic"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.txlBic)
        self.toolBox.addItem(self.pgBankverbindung, _fromUtf8(""))
        self.pgZahlungen = QtGui.QWidget()
        self.pgZahlungen.setGeometry(QtCore.QRect(0, 0, 438, 307))
        self.pgZahlungen.setObjectName(_fromUtf8("pgZahlungen"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pgZahlungen)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblZahlungen = QtGui.QTableView(self.pgZahlungen)
        self.tblZahlungen.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblZahlungen.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tblZahlungen.setObjectName(_fromUtf8("tblZahlungen"))
        self.gridLayout_4.addWidget(self.tblZahlungen, 0, 0, 1, 1)
        self.toolBox.addItem(self.pgZahlungen, _fromUtf8(""))
        self.pgSchreiben = QtGui.QWidget()
        self.pgSchreiben.setGeometry(QtCore.QRect(0, 0, 438, 307))
        self.pgSchreiben.setObjectName(_fromUtf8("pgSchreiben"))
        self.gridLayout_5 = QtGui.QGridLayout(self.pgSchreiben)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblSchreiben = QtGui.QTableWidget(self.pgSchreiben)
        self.tblSchreiben.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblSchreiben.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblSchreiben.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblSchreiben.setColumnCount(3)
        self.tblSchreiben.setObjectName(_fromUtf8("tblSchreiben"))
        self.tblSchreiben.setRowCount(0)
        self.tblSchreiben.horizontalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tblSchreiben, 0, 0, 1, 1)
        self.toolBox.addItem(self.pgSchreiben, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.toolBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Mitglied)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Mitglied)
        self.toolBox.setCurrentIndex(0)
        self.tabKontakt.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Mitglied)
        Mitglied.setTabOrder(self.radNatuerlichePerson, self.radJuristischePerson)
        Mitglied.setTabOrder(self.radJuristischePerson, self.txlStrasse)
        Mitglied.setTabOrder(self.txlStrasse, self.txlHnr)
        Mitglied.setTabOrder(self.txlHnr, self.txlHnrZusatz)
        Mitglied.setTabOrder(self.txlHnrZusatz, self.txlAdresszusatz)
        Mitglied.setTabOrder(self.txlAdresszusatz, self.cbxOrt)
        Mitglied.setTabOrder(self.cbxOrt, self.tabKontakt)
        Mitglied.setTabOrder(self.tabKontakt, self.tblTelefon)
        Mitglied.setTabOrder(self.tblTelefon, self.tblEmail)
        Mitglied.setTabOrder(self.tblEmail, self.txlMitgliedsnummer)
        Mitglied.setTabOrder(self.txlMitgliedsnummer, self.cbxKategorie)
        Mitglied.setTabOrder(self.cbxKategorie, self.cbxBeitragsgruppe)
        Mitglied.setTabOrder(self.cbxBeitragsgruppe, self.txlBeitrag)
        Mitglied.setTabOrder(self.txlBeitrag, self.txlIndividuellerBeitrag)
        Mitglied.setTabOrder(self.txlIndividuellerBeitrag, self.cbxZahlungsart)
        Mitglied.setTabOrder(self.cbxZahlungsart, self.cbxZahlweise)
        Mitglied.setTabOrder(self.cbxZahlweise, self.dateEintrittsDatum)
        Mitglied.setTabOrder(self.dateEintrittsDatum, self.dateAustrittsDatum)
        Mitglied.setTabOrder(self.dateAustrittsDatum, self.btnAustrittHeute)
        Mitglied.setTabOrder(self.btnAustrittHeute, self.cbxAustrittsgrund)
        Mitglied.setTabOrder(self.cbxAustrittsgrund, self.txlKontonummer)
        Mitglied.setTabOrder(self.txlKontonummer, self.txlBlz)
        Mitglied.setTabOrder(self.txlBlz, self.txlInstitut)
        Mitglied.setTabOrder(self.txlInstitut, self.txlKontoInhaber)
        Mitglied.setTabOrder(self.txlKontoInhaber, self.tblZahlungen)
        Mitglied.setTabOrder(self.tblZahlungen, self.buttonBox)

    def retranslateUi(self, Mitglied):
        Mitglied.setWindowTitle(_translate("Mitglied", "Mitglied", None))
        self.radNatuerlichePerson.setText(_translate("Mitglied", "natürliche Person", None))
        self.radJuristischePerson.setText(_translate("Mitglied", "juristischePerson", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgPerson), _translate("Mitglied", "Mitglied", None))
        self.label.setText(_translate("Mitglied", "Straße", None))
        self.label_3.setText(_translate("Mitglied", "Hnr", None))
        self.label_4.setText(_translate("Mitglied", "Zusatz", None))
        self.label_5.setText(_translate("Mitglied", "Adresszusatz", None))
        self.groupBox.setTitle(_translate("Mitglied", "Ort", None))
        self.radOrtCbx.setText(_translate("Mitglied", "vorhandene", None))
        self.radOrtNeu.setToolTip(_translate("Mitglied", "einen neuen Ort erfassen", None))
        self.radOrtNeu.setText(_translate("Mitglied", "neu", None))
        self.labPlz.setText(_translate("Mitglied", "PLZ", None))
        self.labOrt.setText(_translate("Mitglied", "Ort", None))
        self.labLand.setText(_translate("Mitglied", "Land", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgAdresse), _translate("Mitglied", "Adresse", None))
        self.tabKontakt.setTabText(self.tabKontakt.indexOf(self.tabEmail), _translate("Mitglied", "Email", None))
        self.tabKontakt.setTabText(self.tabKontakt.indexOf(self.tabTelefon), _translate("Mitglied", "Telefon/Fax", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgKontakt), _translate("Mitglied", "Kontakt", None))
        self.label_2.setText(_translate("Mitglied", "Mitgliedsnummer", None))
        self.label_13.setText(_translate("Mitglied", "Kategorie", None))
        self.label_7.setText(_translate("Mitglied", "Beitragsgruppe", None))
        self.label_9.setText(_translate("Mitglied", "Beitrag", None))
        self.label_10.setText(_translate("Mitglied", "individueller Beitrag", None))
        self.label_15.setText(_translate("Mitglied", "Zahlungsart", None))
        self.label_17.setText(_translate("Mitglied", "Zahlweise", None))
        self.label_11.setText(_translate("Mitglied", "Eintrittsdatum", None))
        self.dateEintrittsDatum.setDisplayFormat(_translate("Mitglied", "dd.MM.yyyy", None))
        self.label_12.setText(_translate("Mitglied", "Austrittsdatum", None))
        self.dateAustrittsDatum.setDisplayFormat(_translate("Mitglied", "dd.MM.yyyy", None))
        self.btnAustrittHeute.setText(_translate("Mitglied", "heute", None))
        self.lblAustrittsgrund.setText(_translate("Mitglied", "Austrittsgrund", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgMitgliedschaft), _translate("Mitglied", "Mitgliedschaft", None))
        self.label_8.setText(_translate("Mitglied", "Kontonummer", None))
        self.label_14.setText(_translate("Mitglied", "BLZ", None))
        self.label_16.setText(_translate("Mitglied", "Institut", None))
        self.label_18.setText(_translate("Mitglied", "Kontoinhaber", None))
        self.label_19.setText(_translate("Mitglied", "Datum Einzugserm.", None))
        self.dateEinzugsermaechtigung.setDisplayFormat(_translate("Mitglied", "dd.MM.yyyy", None))
        self.btnEinzugsermaechtigungHeute.setText(_translate("Mitglied", "Heute", None))
        self.label_6.setText(_translate("Mitglied", "IBAN", None))
        self.label_20.setText(_translate("Mitglied", "BIC", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgBankverbindung), _translate("Mitglied", "Bankverbindung", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgZahlungen), _translate("Mitglied", "Zahlungen", None))
        self.tblSchreiben.setSortingEnabled(True)
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgSchreiben), _translate("Mitglied", "Schreiben", None))

import resources_rc
