# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(647, 482)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabMitglied = QtGui.QTabWidget(self.centralwidget)
        self.tabMitglied.setTabsClosable(True)
        self.tabMitglied.setMovable(True)
        self.tabMitglied.setObjectName(_fromUtf8("tabMitglied"))
        self.defaultTab = QtGui.QWidget()
        self.defaultTab.setObjectName(_fromUtf8("defaultTab"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/identity_ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMitglied.addTab(self.defaultTab, icon, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabMitglied, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.mnuDatei = QtGui.QMenu(self.menubar)
        self.mnuDatei.setObjectName(_fromUtf8("mnuDatei"))
        self.mnuEinstellungen = QtGui.QMenu(self.mnuDatei)
        self.mnuEinstellungen.setObjectName(_fromUtf8("mnuEinstellungen"))
        self.mnuMitglied_Adresse = QtGui.QMenu(self.mnuEinstellungen)
        self.mnuMitglied_Adresse.setObjectName(_fromUtf8("mnuMitglied_Adresse"))
        self.mnuMitgliedschaft = QtGui.QMenu(self.mnuEinstellungen)
        self.mnuMitgliedschaft.setObjectName(_fromUtf8("mnuMitgliedschaft"))
        self.mnuKontakt = QtGui.QMenu(self.mnuEinstellungen)
        self.mnuKontakt.setObjectName(_fromUtf8("mnuKontakt"))
        self.mnuZahlung = QtGui.QMenu(self.mnuEinstellungen)
        self.mnuZahlung.setObjectName(_fromUtf8("mnuZahlung"))
        self.menuSchreiben = QtGui.QMenu(self.mnuEinstellungen)
        self.menuSchreiben.setObjectName(_fromUtf8("menuSchreiben"))
        self.menuAdresse = QtGui.QMenu(self.mnuEinstellungen)
        self.menuAdresse.setObjectName(_fromUtf8("menuAdresse"))
        self.menuMailserver = QtGui.QMenu(self.mnuEinstellungen)
        self.menuMailserver.setObjectName(_fromUtf8("menuMailserver"))
        self.menuMitglied = QtGui.QMenu(self.menubar)
        self.menuMitglied.setObjectName(_fromUtf8("menuMitglied"))
        self.menuAusgaben = QtGui.QMenu(self.menubar)
        self.menuAusgaben.setObjectName(_fromUtf8("menuAusgaben"))
        self.menuSpezial = QtGui.QMenu(self.menuAusgaben)
        self.menuSpezial.setObjectName(_fromUtf8("menuSpezial"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockMitglieder = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockMitglieder.sizePolicy().hasHeightForWidth())
        self.dockMitglieder.setSizePolicy(sizePolicy)
        self.dockMitglieder.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockMitglieder.setObjectName(_fromUtf8("dockMitglieder"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tblMitglieder = QtGui.QTableView(self.dockWidgetContents)
        self.tblMitglieder.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblMitglieder.setDragEnabled(True)
        self.tblMitglieder.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.tblMitglieder.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblMitglieder.setSortingEnabled(True)
        self.tblMitglieder.setObjectName(_fromUtf8("tblMitglieder"))
        self.tblMitglieder.horizontalHeader().setMinimumSectionSize(6)
        self.verticalLayout_4.addWidget(self.tblMitglieder)
        self.dockMitglieder.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockMitglieder)
        self.dockSuche = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockSuche.sizePolicy().hasHeightForWidth())
        self.dockSuche.setSizePolicy(sizePolicy)
        self.dockSuche.setMaximumSize(QtCore.QSize(524287, 300))
        self.dockSuche.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockSuche.setObjectName(_fromUtf8("dockSuche"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSuche = QtGui.QWidget()
        self.tabSuche.setObjectName(_fromUtf8("tabSuche"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabSuche)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txlFindeMitglied = QtGui.QLineEdit(self.tabSuche)
        self.txlFindeMitglied.setObjectName(_fromUtf8("txlFindeMitglied"))
        self.horizontalLayout.addWidget(self.txlFindeMitglied)
        self.btnFindeMitglied = QtGui.QPushButton(self.tabSuche)
        self.btnFindeMitglied.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnFindeMitglied.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFindeMitglied.setIcon(icon1)
        self.btnFindeMitglied.setFlat(True)
        self.btnFindeMitglied.setObjectName(_fromUtf8("btnFindeMitglied"))
        self.horizontalLayout.addWidget(self.btnFindeMitglied)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 64, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tabSuche, _fromUtf8(""))
        self.tabErweitert = QtGui.QWidget()
        self.tabErweitert.setObjectName(_fromUtf8("tabErweitert"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabErweitert)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lstKriteriumUnd = QtGui.QListWidget(self.tabErweitert)
        self.lstKriteriumUnd.setObjectName(_fromUtf8("lstKriteriumUnd"))
        self.verticalLayout_5.addWidget(self.lstKriteriumUnd)
        self.tabWidget.addTab(self.tabErweitert, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.dockSuche.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockSuche)
        self.actBeenden = QtGui.QAction(MainWindow)
        self.actBeenden.setObjectName(_fromUtf8("actBeenden"))
        self.actMitgliedFinden = QtGui.QAction(MainWindow)
        self.actMitgliedFinden.setObjectName(_fromUtf8("actMitgliedFinden"))
        self.actMitgliedNeu = QtGui.QAction(MainWindow)
        self.actMitgliedNeu.setObjectName(_fromUtf8("actMitgliedNeu"))
        self.actSchreibenVerfassen = QtGui.QAction(MainWindow)
        self.actSchreibenVerfassen.setObjectName(_fromUtf8("actSchreibenVerfassen"))
        self.actionBla = QtGui.QAction(MainWindow)
        self.actionBla.setObjectName(_fromUtf8("actionBla"))
        self.actionOrte = QtGui.QAction(MainWindow)
        self.actionOrte.setObjectName(_fromUtf8("actionOrte"))
        self.actionBeitragsgruppe = QtGui.QAction(MainWindow)
        self.actionBeitragsgruppe.setObjectName(_fromUtf8("actionBeitragsgruppe"))
        self.actionMitgliedsgruppe = QtGui.QAction(MainWindow)
        self.actionMitgliedsgruppe.setObjectName(_fromUtf8("actionMitgliedsgruppe"))
        self.actionAustrittsgrund = QtGui.QAction(MainWindow)
        self.actionAustrittsgrund.setObjectName(_fromUtf8("actionAustrittsgrund"))
        self.actionZahlungsart = QtGui.QAction(MainWindow)
        self.actionZahlungsart.setObjectName(_fromUtf8("actionZahlungsart"))
        self.actionAnrede_2 = QtGui.QAction(MainWindow)
        self.actionAnrede_2.setObjectName(_fromUtf8("actionAnrede_2"))
        self.actionOrt = QtGui.QAction(MainWindow)
        self.actionOrt.setObjectName(_fromUtf8("actionOrt"))
        self.actionLand = QtGui.QAction(MainWindow)
        self.actionLand.setObjectName(_fromUtf8("actionLand"))
        self.actionEMail = QtGui.QAction(MainWindow)
        self.actionEMail.setObjectName(_fromUtf8("actionEMail"))
        self.actionTelefon_Fax = QtGui.QAction(MainWindow)
        self.actionTelefon_Fax.setObjectName(_fromUtf8("actionTelefon_Fax"))
        self.actionBank = QtGui.QAction(MainWindow)
        self.actionBank.setObjectName(_fromUtf8("actionBank"))
        self.actAnrede = QtGui.QAction(MainWindow)
        self.actAnrede.setObjectName(_fromUtf8("actAnrede"))
        self.actBeitragsgruppe = QtGui.QAction(MainWindow)
        self.actBeitragsgruppe.setObjectName(_fromUtf8("actBeitragsgruppe"))
        self.actMitgliedsgruppe = QtGui.QAction(MainWindow)
        self.actMitgliedsgruppe.setObjectName(_fromUtf8("actMitgliedsgruppe"))
        self.actAustrittsgrund = QtGui.QAction(MainWindow)
        self.actAustrittsgrund.setObjectName(_fromUtf8("actAustrittsgrund"))
        self.actZahlungsart = QtGui.QAction(MainWindow)
        self.actZahlungsart.setObjectName(_fromUtf8("actZahlungsart"))
        self.actHinweisEMail = QtGui.QAction(MainWindow)
        self.actHinweisEMail.setObjectName(_fromUtf8("actHinweisEMail"))
        self.actHinweisTelFax = QtGui.QAction(MainWindow)
        self.actHinweisTelFax.setObjectName(_fromUtf8("actHinweisTelFax"))
        self.actBank = QtGui.QAction(MainWindow)
        self.actBank.setObjectName(_fromUtf8("actBank"))
        self.actHinweisZahlung = QtGui.QAction(MainWindow)
        self.actHinweisZahlung.setObjectName(_fromUtf8("actHinweisZahlung"))
        self.actVerbindung = QtGui.QAction(MainWindow)
        self.actVerbindung.setObjectName(_fromUtf8("actVerbindung"))
        self.actInitialisieren = QtGui.QAction(MainWindow)
        self.actInitialisieren.setObjectName(_fromUtf8("actInitialisieren"))
        self.actZahlweise = QtGui.QAction(MainWindow)
        self.actZahlweise.setObjectName(_fromUtf8("actZahlweise"))
        self.actArt = QtGui.QAction(MainWindow)
        self.actArt.setObjectName(_fromUtf8("actArt"))
        self.actSpendenbescheinigung = QtGui.QAction(MainWindow)
        self.actSpendenbescheinigung.setObjectName(_fromUtf8("actSpendenbescheinigung"))
        self.actMahnung = QtGui.QAction(MainWindow)
        self.actMahnung.setObjectName(_fromUtf8("actMahnung"))
        self.actSpeicherpfad = QtGui.QAction(MainWindow)
        self.actSpeicherpfad.setObjectName(_fromUtf8("actSpeicherpfad"))
        self.actErweiterteSuche = QtGui.QAction(MainWindow)
        self.actErweiterteSuche.setObjectName(_fromUtf8("actErweiterteSuche"))
        self.actOrt = QtGui.QAction(MainWindow)
        self.actOrt.setObjectName(_fromUtf8("actOrt"))
        self.actLand = QtGui.QAction(MainWindow)
        self.actLand.setObjectName(_fromUtf8("actLand"))
        self.actSMTP = QtGui.QAction(MainWindow)
        self.actSMTP.setObjectName(_fromUtf8("actSMTP"))
        self.actDatenblatt = QtGui.QAction(MainWindow)
        self.actDatenblatt.setObjectName(_fromUtf8("actDatenblatt"))
        self.actSEPA_Umstellung = QtGui.QAction(MainWindow)
        self.actSEPA_Umstellung.setObjectName(_fromUtf8("actSEPA_Umstellung"))
        self.actLastschrift = QtGui.QAction(MainWindow)
        self.actLastschrift.setObjectName(_fromUtf8("actLastschrift"))
        self.actOpen = QtGui.QAction(MainWindow)
        self.actOpen.setObjectName(_fromUtf8("actOpen"))
        self.actNeu = QtGui.QAction(MainWindow)
        self.actNeu.setShortcut(_fromUtf8(""))
        self.actNeu.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actNeu.setObjectName(_fromUtf8("actNeu"))
        self.actInitialize = QtGui.QAction(MainWindow)
        self.actInitialize.setObjectName(_fromUtf8("actInitialize"))
        self.mnuMitglied_Adresse.addAction(self.actErweiterteSuche)
        self.mnuMitglied_Adresse.addAction(self.actAnrede)
        self.mnuMitgliedschaft.addAction(self.actBeitragsgruppe)
        self.mnuMitgliedschaft.addAction(self.actMitgliedsgruppe)
        self.mnuMitgliedschaft.addAction(self.actAustrittsgrund)
        self.mnuMitgliedschaft.addAction(self.actZahlungsart)
        self.mnuMitgliedschaft.addAction(self.actZahlweise)
        self.mnuKontakt.addAction(self.actHinweisEMail)
        self.mnuKontakt.addAction(self.actHinweisTelFax)
        self.mnuZahlung.addAction(self.actBank)
        self.mnuZahlung.addAction(self.actHinweisZahlung)
        self.menuSchreiben.addAction(self.actSpeicherpfad)
        self.menuAdresse.addAction(self.actOrt)
        self.menuAdresse.addAction(self.actLand)
        self.menuMailserver.addAction(self.actSMTP)
        self.mnuEinstellungen.addAction(self.mnuMitglied_Adresse.menuAction())
        self.mnuEinstellungen.addAction(self.menuAdresse.menuAction())
        self.mnuEinstellungen.addAction(self.mnuMitgliedschaft.menuAction())
        self.mnuEinstellungen.addAction(self.mnuKontakt.menuAction())
        self.mnuEinstellungen.addAction(self.mnuZahlung.menuAction())
        self.mnuEinstellungen.addAction(self.menuSchreiben.menuAction())
        self.mnuEinstellungen.addSeparator()
        self.mnuEinstellungen.addAction(self.menuMailserver.menuAction())
        self.mnuDatei.addAction(self.mnuEinstellungen.menuAction())
        self.mnuDatei.addSeparator()
        self.mnuDatei.addAction(self.actOpen)
        self.mnuDatei.addAction(self.actNeu)
        self.mnuDatei.addAction(self.actInitialize)
        self.mnuDatei.addSeparator()
        self.mnuDatei.addAction(self.actBeenden)
        self.menuMitglied.addAction(self.actMitgliedNeu)
        self.menuMitglied.addAction(self.actMitgliedFinden)
        self.menuSpezial.addAction(self.actSpendenbescheinigung)
        self.menuSpezial.addAction(self.actLastschrift)
        self.menuSpezial.addAction(self.actDatenblatt)
        self.menuSpezial.addAction(self.actMahnung)
        self.menuSpezial.addAction(self.actSEPA_Umstellung)
        self.menuAusgaben.addAction(self.actSchreibenVerfassen)
        self.menuAusgaben.addAction(self.menuSpezial.menuAction())
        self.menubar.addAction(self.mnuDatei.menuAction())
        self.menubar.addAction(self.menuMitglied.menuAction())
        self.menubar.addAction(self.menuAusgaben.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMitglied.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnFindeMitglied, self.tabMitglied)
        MainWindow.setTabOrder(self.tabMitglied, self.txlFindeMitglied)
        MainWindow.setTabOrder(self.txlFindeMitglied, self.lstKriteriumUnd)
        MainWindow.setTabOrder(self.lstKriteriumUnd, self.tblMitglieder)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Mitgliederverwaltung", None))
        self.tabMitglied.setTabText(self.tabMitglied.indexOf(self.defaultTab), _translate("MainWindow", "Vorname Nachname", None))
        self.mnuDatei.setTitle(_translate("MainWindow", "&Datei", None))
        self.mnuEinstellungen.setTitle(_translate("MainWindow", "&Einstellungen", None))
        self.mnuMitglied_Adresse.setTitle(_translate("MainWindow", "Mitglied", None))
        self.mnuMitgliedschaft.setTitle(_translate("MainWindow", "Mitgliedschaft", None))
        self.mnuKontakt.setTitle(_translate("MainWindow", "Kontakt", None))
        self.mnuZahlung.setTitle(_translate("MainWindow", "Zahlung", None))
        self.menuSchreiben.setTitle(_translate("MainWindow", "Schreiben", None))
        self.menuAdresse.setTitle(_translate("MainWindow", "Adresse", None))
        self.menuMailserver.setTitle(_translate("MainWindow", "Mailserver", None))
        self.menuMitglied.setTitle(_translate("MainWindow", "&Mitglied", None))
        self.menuAusgaben.setTitle(_translate("MainWindow", "&Schreiben", None))
        self.menuSpezial.setTitle(_translate("MainWindow", "&Spezial", None))
        self.dockMitglieder.setWindowTitle(_translate("MainWindow", "Mitglieder", None))
        self.dockSuche.setWindowTitle(_translate("MainWindow", "Suchen", None))
        self.txlFindeMitglied.setToolTip(_translate("MainWindow", "Name oder Mitgliedsnummer eingeben", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSuche), _translate("MainWindow", "Suche", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabErweitert), _translate("MainWindow", "Erweitert", None))
        self.actBeenden.setText(_translate("MainWindow", "&beenden", None))
        self.actMitgliedFinden.setText(_translate("MainWindow", "&Finden", None))
        self.actMitgliedNeu.setText(_translate("MainWindow", "&Aufnehmen", None))
        self.actSchreibenVerfassen.setText(_translate("MainWindow", "&Verfassen", None))
        self.actionBla.setText(_translate("MainWindow", "bla", None))
        self.actionOrte.setText(_translate("MainWindow", "Ort", None))
        self.actionBeitragsgruppe.setText(_translate("MainWindow", "Beitragsgruppe", None))
        self.actionMitgliedsgruppe.setText(_translate("MainWindow", "Mitgliedsgruppe", None))
        self.actionAustrittsgrund.setText(_translate("MainWindow", "Austrittsgrund", None))
        self.actionZahlungsart.setText(_translate("MainWindow", "Zahlungsart", None))
        self.actionAnrede_2.setText(_translate("MainWindow", "Anrede", None))
        self.actionOrt.setText(_translate("MainWindow", "Ort", None))
        self.actionLand.setText(_translate("MainWindow", "Land", None))
        self.actionEMail.setText(_translate("MainWindow", "EMail", None))
        self.actionTelefon_Fax.setText(_translate("MainWindow", "Hinweise Telefon/Fax", None))
        self.actionBank.setText(_translate("MainWindow", "Bank", None))
        self.actAnrede.setText(_translate("MainWindow", "Anrede", None))
        self.actBeitragsgruppe.setText(_translate("MainWindow", "Beitragsgruppen", None))
        self.actMitgliedsgruppe.setText(_translate("MainWindow", "Mitgliedsgruppen", None))
        self.actAustrittsgrund.setText(_translate("MainWindow", "Austrittsgrund", None))
        self.actZahlungsart.setText(_translate("MainWindow", "Zahlungsart", None))
        self.actHinweisEMail.setText(_translate("MainWindow", "Hinweis EMail", None))
        self.actHinweisTelFax.setText(_translate("MainWindow", "Hinweis Tel/Fax", None))
        self.actBank.setText(_translate("MainWindow", "Bank", None))
        self.actHinweisZahlung.setText(_translate("MainWindow", "Hinweis Zahlung", None))
        self.actVerbindung.setText(_translate("MainWindow", "Verbindung", None))
        self.actInitialisieren.setText(_translate("MainWindow", "Initialisieren", None))
        self.actZahlweise.setText(_translate("MainWindow", "Zahlweise", None))
        self.actArt.setText(_translate("MainWindow", "Art", None))
        self.actSpendenbescheinigung.setText(_translate("MainWindow", "&Spendenbescheinigung", None))
        self.actMahnung.setText(_translate("MainWindow", "&Mahnung", None))
        self.actSpeicherpfad.setText(_translate("MainWindow", "Speicherpfad", None))
        self.actErweiterteSuche.setText(_translate("MainWindow", "Erweiterte Suche", None))
        self.actOrt.setText(_translate("MainWindow", "Ort", None))
        self.actLand.setText(_translate("MainWindow", "Land", None))
        self.actSMTP.setText(_translate("MainWindow", "Postausgangsserver (SMTP)", None))
        self.actDatenblatt.setText(_translate("MainWindow", "&Datenblatt", None))
        self.actSEPA_Umstellung.setText(_translate("MainWindow", "SEPA-Umstellung", None))
        self.actLastschrift.setText(_translate("MainWindow", "Ankündigung &Lastschrift", None))
        self.actOpen.setText(_translate("MainWindow", "&Öffnen...", None))
        self.actNeu.setText(_translate("MainWindow", "&Neu...", None))
        self.actInitialize.setText(_translate("MainWindow", "&Initialisieren", None))

import resources_rc
